packages:
  - "."
  - ".dependencies/vega"
  - ".dependencies/vega/packages/protocol"
  - ".dependencies/vega-plugin-richtext"
  - ".dependencies/vega-plugin-richtext-html"

linkWorkspacePackages: true

allowBuilds:
  esbuild: true

